BEGIN;

TRUNCATE
    "comments",
    "unions",
    "industry";


INSERT INTO "industry" ("id", "industry")
VALUES
    (1, 'Entertainment'),
    (2, 'Travel'),
    (3, 'Transportation'),
    (4, 'Government'),
    (5, 'Education'),
    (6, 'Communication'),
    (7, 'Food'),
    (8, 'Farming'),
    (9, 'Industrial'),
    (10, 'Engineering'),
    (11, 'Mechanics'),
    (12, 'Construction'),
    (13, 'Medical'),
    (14, 'Sports'),
    (15, 'Business'),
    (16, 'Service'),
    (17, 'Manufacturing'),
    (18, 'Mining'),
    (19, 'Utility'),
    (20, 'Emergency Service');
    

INSERT INTO "unions" ("name", "industry", "desc", "webURL")
VALUES
    ('Actors'' Equity Association', 1, 'A labor union representing American actors and stage managers in the theatre.', 'https://www.actorsequity.org/'),
    ('Air Line Pilots Association', 2, 'The largest airline pilot union, ALPA represents and advocates for pilots at US and Canadian airlines.', 'http://www.alpa.org/'),
    ('Amalgamated Transit Union', 3, 'The largest labor union representing transit and allied workers in the US and Canada.', 'https://www.atu.org/'),
    ('American Federation of Government Employees', 4, 'The AFGE is the largest federal employee union and represents federal and D.C. government workers nationwide and overseas.', 'https://www.afge.org/'),
    ('American Federation of Musicians of the United States and Canada', 1, 'A union for "any musician who receives pay for his musical services", the AFM is the largest union of musicians in the world.', 'https://www.afm.org/'),
    ('American Federation of School Administrators', 5, 'The AFSA is the national labor union for administrators, professionals, and supervisors in America.', 'https://www.theschoolleader.org/'),
    ('American Federation of State, County, and Municipal Employees', 4, 'A union of local government employees formed with the purpose "to promote, defend, and enhance the civil service system."', 'http://www.afscme.org/'),
    ('American Federation of Teachers', 5, 'A union which represents teachers and other education professionals.', 'http://www.aft.org/'),
    ('American Postal Workers Union', 19, 'A union which represents USPS and private-sector mail workers and retirees.', 'http://www.apwu.org/'),
    ('American Radio Association', 6, 'A union which represents seagoing radio operators, Electronic Officers, and Master Electronic Officers employed on US flag merchant vessels.', 'http://www.americanradioassociation.org/'),
    ('American Train Dispatchers Association', 3, 'The ATDA represents employees in the United States'' railroad industry in charge of dispatching trains and supplying electric power for railroads to be used in train propulsion and signalling.', 'http://www.atda.org/'),
    ('American Guild of Musical Artists', 1, 'The labor organization that represents the artists who create America''s operatic, choral, and dance heritage.', 'http://www.musicalartists.org/'),
    ('American Guild of Variety Artists', 1, ' A union founded to represent performing Artists and Stage Managers in live performances in the Variety field.', 'http://www.agvausa.com/'),
    ('The Guild of Italian American Actors', 1, 'The only ethnic acting union in the United States, the GIAA supports a broad range of arts groups that are working to preserve their cultural heritage.', 'http://www.giaa.us/'),
    ('Bakery, Confectionery, Tobacco Workers and Grain Millers International Union', 7, 'An organization which represents workers employed by some of America''s largest corporations in the supply and production of food and other agricultural products.', 'http://bctgm.org/'),
    ('Brotherhood of Railroad Signalmen', 3, 'A trade union representing railroad employees who install and maintain signal systems for the nation''s railroads.', 'http://www.brs.org/'),
    ('California School Employees Association', 5, 'A union serving classified school employees in the State of California.', 'http://www.csea.com/'),
    ('Communications Workers of America', 6, 'The CWA serves workers in the private and public sector working in various industries dealing with communications.', 'http://www.cwa-union.org/'),
    ('Association of Flight Attendants', 2, 'The AFA is the flight attendant union organized by flight attendants for flight attendants.', 'http://www.afacwa.org/'),
    ('Industrial Union of Electronic Workers', 17, 'The IUE is the dominant industrial union representing workers in the electrical-electronics manufacturing sector.', 'http://www.iue-cwa.org/'),
    ('National Association of Broadcast Employees and Technicians', 6, 'The NABET-CWA represents workers in broadcasting and related industries.', 'http://www.nabetcwa.org/'),
    ('Printing, Publishing and Media Workers', 6, 'A union that represents workers in the printing, publishing, and media industries.', 'http://www.cwa-ppmws.org/index.cfm'),
    ('The Newspaper Guild', 6, 'A union for journalists and media workers.', 'http://newsguild.org/'),
    ('Farm Labor Organizing Committee', 8, 'The FLOC represents migrant farmworkers and aims to even the power distribution of the farming industry.', 'http://www.floc.com/wordpress'),
    ('International Alliance of Theatrical Stage Employees, Moving Picture Technicians, Artists and Allied Crafts of the United States, Its Territories and Canada', 1, 'The IATSE supports workers in the entertainment industry, including behind-the-scenes workers from animators to theater ushers.', 'http://www.iatse-intl.org/home.html'),
    ('International Association of Bridge, Structural, Ornamental and Reinforcing Iron Workers', 12, 'The IW represents ironworkers who work on bridges, structural steel, ornamental, architectural, and miscellaneous metals, rebar and in shops.', 'http://www.ironworkers.org/'),
    ('International Association of Fire Fighters', 20, 'The IAFF represents professional fire fighters and paramedics across the United States and Canada', 'http://www.iaff.org/'),
    ('International Association of Heat and Frost Insulators and Allied Workers', 9, 'An organization designed to assist professional insulators in securing employment and defend their rights as workers.', 'http://www.insulators.org/'),
    ('International Association of Machinists and Aerospace Workers', 11, 'A union which serves Machinists working in Aerospace, Transportation and various other industries.', 'http://www.goiam.org/'),
    ('National Federation of Federal Employees', 4, 'The NFFE is a national union representing blue and white collar government workers across the United States.', 'http://nffe.org/'),
    ('Transportation Communications International Union/IAM', 3, 'The TCU/IAM represents people employed in transportation jobs, mostly in the railroad industry. Members perform various jobs including: clerks, computer programmers, and on-board service workers.', 'http://www.goiam.org/index.php/tcunion'),
    ('International Association of Sheet Metal, Air, Rail and Transportation Workers', 9, 'A union for sheet metal workers, service technicians, bus operators, engineers, conductors, sign workers, welders, production employees and more.', 'http://smart-union.org/'),
    ('International Brotherhood of Boilermakers, Iron Ship Builders, Blacksmiths, Forgers and Helpers', 9, 'An elite membership of skilled craftsmen and women and industrial workers, trained and committed to stand apart as the best.', 'http://www.boilermakers.org/'),
    ('International Brotherhood of Electrical Workers', 9, 'A union representing workers in a wide variety of fields, including utilities, construction, telecommunications, broadcasting, manufacturing, railroads, and government.', 'http://www.ibew.org/'),
    ('International Federation of Professional and Technical Engineers', 10, 'IFPTE is a union for professional engineers, scientists, nonprofit employees, technicians, lawyers and more.', 'http://www.ifpte.org/'),
    ('International Organization of Masters, Mates & Pilots', 2, 'The members of the MM&P include the world''s best qualified and most highly trained professional mariners.', 'https://bridgedeck.org/'),
    ('International Union of Allied, Novelty and Production Workers', 17, 'This union covers workers employed in general manufacturing and related industries.', 'http://iuanpw.org/'),
    ('International Union of Bricklayers and Allied Craftworkers', 12, 'BAC represents the most highly skilled trowel trades craftworkers across the United States and Canada, including bricklayers, stone and marble masons, cement masons, plasterers, tilesetters, terrazzon and mosaic workers, and pointers/cleaners/caulkers.', 'http://www.bacweb.org/'),
    ('International Union of Elevator Constructors', 12, 'The IUEC is an organization designed to promote and protect the interests of elevator constructors across America.', 'https://www.iuec.org/'),
    ('International Union of Operating Engineers', 9, 'The IUOE is a progressive, diversified trade union that primarily represents operating engineers who work as heavy equipment operators, mechanics, and surveyors in the construction industry and in the service industries.', 'http://www.iuoe.org/'),
    ('International Union of Painters and Allied Trades of the United States and Canada', 12, 'The IUPAT represents people who work in the Finishing Trades in the United States and Canada, including industrial and commercial painting, drywall finishing, glazing and glasswork, and several others.', 'http://www.iupat.org/'),
    ('Laborers'' International Union of North America', 12, 'LiUNA is a union of skilled and experienced workers trained to work safely in the construction and energy industries.', 'http://www.liuna.org/'),
    ('National Postal Mail Handlers Union', 19, 'The NPMHU is recognized as the exclusive collective bargaining agent for 47,000 Mail Handlers employed by the USPS', 'http://www.npmhu.org/'),
    ('Marine Engineers'' Beneficial Association', 10, 'The MEBA is the nation''s oldest and finest maritime labor union.', 'http://www.mebaunion.org/'),
    ('Professional Aviation Safety Specialists', 3, 'PASS represents employees of the Federal Aviation Administration and Department of Defense who install, maintain, support, and certify air traffic control and national defense equipment and work in other areas pertaining to aviation and national defense in the United States and abroad.', 'http://www.passnational.org/'),
    ('National Air Traffic Controllers Association', 3, 'NATCA is a labor union and aviation safety organization in the United States that represents air traffic controllers, engineers, and other aviation safety-related professionals.', 'http://www.natca.org/'),
    ('National Association of Letter Carriers', 19, 'The NALC is the sole representative of city delivery letter carriers employed by the USPS.', 'http://www.nalc.org/'),
    ('National Nurses United', 13, 'The NNU is the largest union and professional association of registered nurses in US history.', 'http://www.nationalnursesunited.org/'),
    ('National Taxi Workers Alliance', 3, 'The NTWA is an alliance of yellow cab, green car,  black car, livery and app-dispatched drivers.', 'http://www.nytwa.org/'),
    ('NFL Players Association', 14, 'A union which represents the players of the National Football League.', 'https://www.nflpa.com/'),
    ('Office and Professional Employees International Union', 15, 'OPEIU represents employees and independent contractors in credit unions, hospitals and medical clinics, insurance, higher education, transportation, shipping, utilities, hotels, administrative offices and more.', 'http://www.opeiu.org/'),
    ('Operative Plasterers'' and Cement Masons'' International Association of the United States and Canada', 12, 'The OPCMIA has represented and trained plasterers and cement masons since 1864.', 'http://www.opcmia.org/'),
    ('Screen Actors Guild-American Federation of Television and Radio Artists', 1, 'SAG-AFTRA represents actors, announcers, broadcast journalists, dancers, DJs, news writers, news editors, program hosts, puppeteers, recording artists, singers, stunt performers, voiceover actors and other media professionals.', 'http://www.sagaftra.org/'),
    ('Seafarers International Union of North America', 3, 'The SIU represents professional United States merchant mariners sailing aboard US-flag vessels in the deep sea, Great Lakes and inland trades.', 'http://www.seafarers.org/'),
    ('Transport Workers Union of America', 3, 'The TWU works for the rights of transit and railroad workers across America.', 'http://www.twu.org/'),
    ('United Association of Journeymen and Apprentices of the Plumbing and Pipe Fitting Industry of the United States and Canada', 12, 'The UA represents plumbers, pipefitters, sprinkler fitters, service technicians, and welders across North America.', 'http://www.ua.org/'),
    ('United Automobile, Aerospace & Agricultural Implement Workers of America International Union', 17, 'UAW-represented workplaces range from multinational corporations, small manufacturers and state and local governments, to colleges and universities, hospitals and private non-profit orgainizations.', 'http://www.uaw.org/'),
    ('United Food and Commercial Workers International Union', 16, 'The UFCW represents retail and grocery workers as well as various other service and essential workers across the US.', 'http://www.ufcw.org/'),
    ('Retail, Wholesale and Department Store Union', 16, 'The RWDSU serves many workers in the retail and wholesale manufacturing industries.', 'http://rwdsu.info/'),
    ('United Mine Workers of America', 18, 'The UMWA serves a diverse community of coal miners, manufacturing workers, clean coal technicians, health care workers and more throughout the US and Canada.', 'http://www.umwa.org/'),
    ('United Steel, Paper and Forestry, Rubber, Manufacturing, Energy, Allied Industrial & Service Workers International Union', 17, 'The USW serves workers in a variety of industries including health care and manufacturing, as well as energy and transportation.', 'http://www.usw.org/'),
    ('Glass, Molders, Pottery, Plastics & Allied Workers International Union', 17, 'A subset of the USW, the GMP-USW primarily serves workers in glass, foundries, molding, plastics, and pottery as well as ceramics, china, fiberglass, and insulation.', 'http://www.gmpiu.org/'),
    ('United Union of Roofers, Waterproofers and Allied Workers', 12, 'The union represents members who apply all types of roofing and waterproofing systems.', 'http://www.unionroofers.com/'),
    ('Utility Workers Union of America', 19, 'The UWUA represents utility workers in several industries including electric, gas, water, and more.', 'http://uwua.net/'),
    ('Writers Guild of America, East', 6, 'The WGAE is a labor union representing those who write content for motion pictures, television, news and digital media.', 'http://www.wgaeast.org/');

COMMIT;